#!/usr/bin/env bash
#Write a Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line, using while loop;.

str="Best School"
i=1
while [ $i -le 10 ]
do
echo "$str"
if [ $i == 9 ]
then
echo "Hi"
fi
((i++))
done
